import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#353438",
        "primary": "#b4c5ff",
        "on-tertiary": "#581e00",
        "on-background": "#e4e1e6",
        "inverse-on-surface": "#303033",
        "on-primary": "#002a78",
        "secondary-container": "#4a4b53",
        "on-error": "#690005",
        "on-secondary-fixed": "#1a1b22",
        "surface-variant": "#353438",
        "on-tertiary-fixed": "#360f00",
        "primary-container": "#2563eb",
        "on-tertiary-container": "#ffede6",
        "surface-container-lowest": "#0e0e11",
        "secondary-fixed": "#e3e1ec",
        "surface-container": "#1f1f22",
        "tertiary-container": "#bc4800",
        "primary-fixed-dim": "#b4c5ff",
        "error": "#ffb4ab",
        "on-secondary-container": "#bcbbc5",
        "on-primary-fixed": "#00174b",
        "on-primary-fixed-variant": "#003ea8",
        "outline-variant": "#434655",
        "secondary-fixed-dim": "#c6c5cf",
        "tertiary-fixed-dim": "#ffb596",
        "on-surface-variant": "#c3c6d7",
        "surface-container-high": "#2a2a2d",
        "on-surface": "#e4e1e6",
        "tertiary-fixed": "#ffdbcd",
        "on-secondary-fixed-variant": "#46464e",
        "secondary": "#c6c5cf",
        "inverse-surface": "#e4e1e6",
        "inverse-primary": "#0053db",
        "surface-tint": "#b4c5ff",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-primary-container": "#eeefff",
        "on-secondary": "#2f3038",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "surface-dim": "#131316",
        "surface-container-low": "#1b1b1e",
        "primary-fixed": "#dbe1ff",
        "surface-bright": "#39393c",
        "background": "#131316",
        "tertiary": "#ffb596",
        "outline": "#8d90a0",
        "surface": "#131316"
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "40px",
        "2xl": "64px",
        "margin": "32px",
        "gutter": "24px",
      },
      fontFamily: {
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "code-md": ["Geist Mono", "monospace"],
        "code-sm": ["Geist Mono", "monospace"],
        "label-md": ["Geist", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "code-md": ["14px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "code-sm": ["12px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-md": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
};
export default config;
